import fs from "node:fs";
import path from "node:path";
import metaJson from "@/app/_ported/meta.json";

type Meta = { title: string; description: string };
const meta = metaJson as Record<string, Meta>;

// Reads a ported body fragment (generated by scripts/port-newcampux.mjs).
// Runs at build time, which is compatible with `output: export`.
export function fragment(name: string): string {
  return fs.readFileSync(
    path.join(process.cwd(), "app", "_ported", `${name}.html`),
    "utf8"
  );
}

const siteUrl = "https://campux.co";

// Per-page Metadata built from the finished pages' own <title>/<description>.
// `title.absolute` bypasses the layout's "%s | Campux" template because the
// ported titles are already complete.
export function pageMeta(name: string, canonicalPath: string) {
  const m = meta[name] ?? { title: "Campux", description: "" };
  return {
    title: { absolute: m.title },
    description: m.description,
    alternates: { canonical: `${siteUrl}${canonicalPath}` },
    openGraph: {
      title: m.title,
      description: m.description,
      url: `${siteUrl}${canonicalPath}`,
      siteName: "Campux",
      type: "website" as const,
    },
  };
}
